singlepage-layout
rereal7/mcoding pull request #1
Opened 2021-02-07 01:59 UTC by rereal7

レスポンシブデザインの手前まで出来上がったので、確認お願いします。

2021-02-07 02:27 UTC, okohs requested changes
ほぼHTMLよりCSSの修正だけど、どこを修正すべきかの指定がしやすいので全部HTMLファイルの方でコメントしました！確認お願いします。

2021-02-07 02:27 UTC, okohs commented on singlepage-layout/index.html
> +      <a class="button" href="#about" >LEARN MORE</a>
サンプルサイトでは、SEND MESSAGEだけでなく、LEARN MOREにマウスオーバーしたときもopacityがかかっていそうです。opacityの実装を確認してください。

2021-02-07 02:27 UTC, okohs commented on singlepage-layout/index.html
> +    <he class="heading">WORKS</he>
WORKSにあたっているフォントだけ太字になっていません。フォントの設定を確認してください。

2021-02-07 02:27 UTC, okohs commented on singlepage-layout/index.html
>          <div class="skill-title">IDEA</div>
`skill-title` と `skill-text` のフォントサイズが同じになっています。仕様を確認してください。

2021-02-07 02:27 UTC, okohs commented on singlepage-layout/index.html
> +          その先まで考える事を意識しています。
ここ、写しミスになってます。2行目以降はこちらかと
```
新しいことを思いついては試しています。
ディレクションの経験もあります。
```

2021-02-07 02:27 UTC, okohs commented on singlepage-layout/index.html
>    <section class="contact" id="contact">
サンプルサイトと比較すると、見出しの「CONTACT」が必要そうです！

2021-02-07 04:09 UTC, okohs commented
PR書くときにどういう指定で作ったのかがわかるリンクがあると良いので、
今回だとサンプルサイトのURLが書いてあるとよき！
```
レスポンシブデザインの手前まで出来上がったので、確認お願いします。
本のデモページ：http://www.shoeisha.com/book/hp/mcoding/3/
```

2021-02-11 12:11 UTC, rereal7 commented on singlepage-layout/index.html
> +      <a class="button" href="#about" >LEARN MORE</a>
修正しました。

2021-02-11 12:12 UTC, rereal7 commented on singlepage-layout/index.html
> +    <he class="heading">WORKS</he>
修正しました。

2021-02-11 12:33 UTC, rereal7 commented on singlepage-layout/index.html
> +          その先まで考える事を意識しています。
修正しました。

2021-02-11 12:36 UTC, rereal7 commented on singlepage-layout/index.html
>    <section class="contact" id="contact">
修正しました。

2021-02-11 12:39 UTC, rereal7 commented on singlepage-layout/index.html
>          <div class="skill-title">IDEA</div>
修正しました。

2021-02-11 12:49 UTC, okohs approved these changes
修正おつかれさま！LGTM
![20200304-115748-header-696x690](https://user-images.githubusercontent.com/10089070/107638456-f4161b00-6cb2-11eb-8a0f-0112d9b9a0fe.jpg)

2021-02-11 12:50 UTC, merged